### ISSUE TITLE
Error running Assemble

### ISSUE THREAD

**Issue by gakimball** [faustgertz/sassy-ink#4]
A few of us at ZURB testing this framework have gotten this error on the default Grunt task after cloning the repo.

```
Running "shell:makeStage" (shell) task

Running "assemble:docsDev" (assemble) task
Assembling build/docs/docs/examples/images.html ERROR
Warning: The partial ink could not be found Use --force to continue.
```

This is after doing the following to set up the framework:

```
git clone
npm install
bundle
bundle exec grunt
```

Hope y'alls can help :) Thanks for your time!

**Comment by faustgertz** [comment]
That is because there is no `css/ink.css` yet. To create it, try running `grunt sass:dist` or `bundle exec grunt sass:dist` before running `bundle exec grunt`.

Note: While I did not modify ZURB's grunt tasks, I did create sassy versions of them, save the default one:
```
grunt.registerTask('sassy:make:templates', ['sass:dist', 'make:templates']);
grunt.registerTask('sassy:deploy:downloads', ['shell:makeStage', 'sass:dist', 'copy:sassDeploy', 'assemble:templates', 'shell:zipTemplates', 'shell:zipFramework', 'shell:linkFramework', 'shell:deployDownloads', 'shell:cleanUp']);
grunt.registerTask('sassy:make:docs', ['sass:dist', 'make:docs']);
grunt.registerTask('sassy:deploy:docs', ['sass:dist', 'deploy:docs']);
```
I'll add
```
grunt.registerTask('sassy:default', ['sass:dist', 'default']);
```
for completeness. Then you can run `bundle exec grunt sassy:default` and things *should* work as expected.

Please let me know if this helps and how else I can help.

**Comment by gakimball** [comment]
Thanks for your help!
